const SHELTERS_REQUESTED = 'SHELTERS_REQUESTED';
const SHELTERS_RECEIVED = 'SHELTERS_RECEIVED';
const MARKERS_RECEIVED = 'MARKERS_RECEIVED';
const SHELTER_SELECTION_TOGGLED = 'SHELTER_SELECTION_TOGGLED'
const MARKER_SHELTERS_TOGGLED = 'MARKER_SHELTERS_TOGGLED';
const ALL_SHELTERS_TOGGLED = 'ALL_SHELTERS_TOGGLED';
const SHELTER_LIST_ITEM_HOVERED = 'SHELTER_LIST_ITEM_HOVERED';

export {
  SHELTERS_REQUESTED,
  SHELTERS_RECEIVED,
  MARKERS_RECEIVED,
  SHELTER_SELECTION_TOGGLED,
  MARKER_SHELTERS_TOGGLED,
  ALL_SHELTERS_TOGGLED,
  SHELTER_LIST_ITEM_HOVERED
}