const PETS_REQUESTED = 'PETS_REQUESTED';
const PETS_RECEIVED = 'PETS_RECEIVED';
// const SET_ACTIVE_PET_FILTERS = 'SET_ACTIVE_PET_FILTERS';
// const MORE_PETS_REQUESTED = 'MORE_PETS_REQUESTED';
const MORE_PETS_RECEIVED = 'MORE_PETS_RECEIVED';

export {
  PETS_REQUESTED,
  PETS_RECEIVED,
  MORE_PETS_RECEIVED
}